# Generated by Django 4.2.4 on 2023-08-15 05:43

import cities_income.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.CharField(max_length=30, unique=True, verbose_name="Город"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanProfit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profit", models.IntegerField(verbose_name="Сумма прибыли (план)")),
                (
                    "year",
                    models.IntegerField(
                        unique=True,
                        validators=[cities_income.validators.validate_year],
                        verbose_name="Год",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_profit",
                        to="cities_income.cities",
                        verbose_name="Город",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActualProfit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profit", models.IntegerField(verbose_name="Сумма прибыли (факт)")),
                (
                    "year",
                    models.IntegerField(
                        unique=True,
                        validators=[cities_income.validators.validate_year],
                        verbose_name="Год",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_profit",
                        to="cities_income.cities",
                        verbose_name="Город",
                    ),
                ),
            ],
        ),
    ]
