# Generated by Django 4.2.4 on 2023-08-15 05:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "cities_income",
            "0002_alter_actualprofit_options_alter_cities_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="planprofit",
            unique_together={("year", "city")},
        ),
    ]
